sonar.organization=e-commerce-web-application
sonar.projectKey=E-Commerce-Web-Application_Cart-Service
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, **/*.test.js
